[package]
name = "termpixels"
description = "A work in progress TUI framework."
readme = "README.md"
repository = "https://github.com/sayanarijit/termpixels"
version = "0.1.0"
authors = ["Arijit Basu <sayanarijit@gmail.com>"]
edition = "2018"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "*"
termion = "*"
